[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "ignorepy_sprousecal"
version = "0.0.7"
dependencies = [
    "requests",
    "rich",
    "pyperclip"
]

[project.scripts]
ignorepy = "ignorepy_sprousecal.genignore"
